[package]
name = "rocker"
version = "0.2.6"
authors = ["Maxim Molchanov <m.molchanov@vonmo.com>"]
license = "MIT/Apache-2.0"
edition = "2018"

[lib]
name = "rocker"
crate-type = ["dylib"]

[dependencies]
lazy_static = "1.4.0"
rustler_sys = "2.2.0"
rocksdb = { git = "https://github.com/Elzor/rust-rocksdb.git", branch = "stable_5.14.2" }